spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---

spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: http://localhost:9200

---

spring:
  config:
    activate:
      on-profile: k8s
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}