name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Test Frontend
      working-directory: frontend.gitops/gitops
      run: |
        npm install
        npm test
        
    - name: Build Frontend
      run: |
        docker build -t $DOCKER_USERNAME/frontend:latest frontend.gitops/gitops
        docker push $DOCKER_USERNAME/frontend:latest
      #Tests
    - name: Test Backend
      working-directory: backend.gitops
      run: |
        ./gradlew test
        
    - name: Build Backend
      run: |
        docker build -t $DOCKER_USERNAME/backend:latest ./backend.gitops
        docker push $DOCKER_USERNAME/backend:latest