name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Frontend
      working-directory: ./frontend.gitops/gitops 
      run: |
        docker build -t $DOCKER_USERNAME/frontend:latest .
        docker push $DOCKER_USERNAME/frontend:latest

    - name: Build Backend
      run: |
        docker build -t $DOCKER_USERNAME/backend:latest ./backend.gitops
        docker push $DOCKER_USERNAME/backend:latest

    # Hier kommt der optionale Kubernetes-Teil
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to Kubernetes
      run: |
        kubectl rollout restart deployment frontend
        kubectl rollout restart deployment backend